version: "3.8"
services:
  dev_db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: serve
    ports:
      - 5432:5432
    volumes:
      - ./server/migrations:/migrations
