DROP TABLE IF EXISTS accounts;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS registrations;
DROP TABLE IF EXISTS ages;
DROP TABLE IF EXISTS project_skills;
DROP TABLE IF EXISTS project_tools;
DROP TYPE IF EXISTS status;